/*
 * This source file was generated by the Gradle 'init' task
 */
package org.battleship;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.io.StringReader;

class AppTest {
    @Test
    void test_read_placement() throws IOException {
        // StringReader: we can construct it with a String,
        // and then read from it like an input stream.
        StringReader sr = new StringReader("B2V\nC8H\na4v\n");
        ByteArrayOutputStream bytes = new ByteArrayOutputStream(); // to collect the output
        // ps writes its data into bytes instead of to the screen
        PrintStream ps = new PrintStream(bytes, true);

        Board<Character> b = new BattleShipBoard<Character>(10, 20);
        App app = new App(b, sr, ps);

        String prompt = "Please enter a location for a ship:";
        Placement[] expected = new Placement[3];
        expected[0] = new Placement(new Coordinate(1, 2), 'V');
        expected[1] = new Placement(new Coordinate(2, 8), 'H');
        expected[2] = new Placement(new Coordinate(0, 4), 'V');

        //  get those three Placements from app.readPlacement
        for (int i = 0; i < expected.length; i++) {
            Placement p = app.readPlacement(prompt);
            assertEquals(p, expected[i]); //did we get the right Placement back
            assertEquals(prompt + "\n", bytes.toString()); //should have printed prompt and newline
            bytes.reset(); //clear out bytes for next time around
        }
    }
}
